### ISSUE TITLE
HTML report plugin is crashing when generating the spec html reports

### ISSUE THREAD

**Issue by saritapol13** [getgauge/html-report#120] opened 2017-01-03 13:14 UTC
### Expected behavior
spec html reports should be generated without any issues

### Actual behavior
Plugin [Html Report] with pid [7365] did not exit after 10.00 seconds. Forcefully killing it.
Specifications:	863 executed	793 passed	70 failed	0 skipped
Scenarios:	863 executed	793 passed	70 failed	0 skipped

I saw that only 111 spec html reports are available. In index.html I see the hyperlinks being created but actual spec htmls are not there

### Steps to reproduce
Tests ran on linux machine
[index.txt](https://github.com/getgauge/html-report/files/682269/index.txt)

Plugins
-------
html-report (3.0.0)
java (0.5.2)

### Gauge version
Gauge version: 0.7.1
Gauge is built from multithreading branch code
Gauge and Gauge-java both are built from multithreading branch code

**Comment by saritapol13** [comment] 2017-01-04 06:07
Performed another run and again facing the same issue. 
Plugin [Html Report] with pid [16765] did not exit after 10.00 seconds. Forcefully killing it.
Specifications:	863 executed	530 passed	333 failed	0 skipped
Scenarios:	863 executed	530 passed	333 failed	0 skipped

**Comment by saritapol13** [comment] 2017-01-04 06:31
I figured out that the gauge.properties stored in /usr/local/share/gauge/gauge.properties was being used. I believed that the property value from the env folder  from the file default.properties will be picked. This is not happening.

**Comment by BugDiver** [comment] 2017-01-04 06:36
@saritapol13 

The issue is that html-report plugin is being killed by Gauge, even before the report generation completes. Since there are huge number of specs, the `plugin_kill_timeout` in `GAUGE_INSTALL_LOCATION/gauge/gauge.properties` should be increased.

Can you try pulling the latest changes from the Gauge multithreading branch you using and then change the value of `plugin_kill_timeout` to `80000` or more?

**Comment by saritapol13** [comment] 2017-01-04 06:41
@BugDiver sure will take the latest changes and increase the plugin_kill_timeout value. On a side note there should be a way where this information is stored and by just running the html report plugin I should have a way to generate the reports.  Currently I need to run the entire regression once again :(

**Comment by apoorvam** [comment] 2017-01-06 09:09
@saritapol13 
* The performance of report generation is now optimized by around 70-90%. #121 This will be part of next release. Nightlies are available if you would like to try.
* Have raised a separate issue #124 to address the generation of reports from previous execution data. Any comments on it can be added there.

Closing it as this issue is fixed.

**Comment by sriv** [comment] 2018-09-07 02:17
reopening this as per @thunderforge's [report on gitter](https://gitter.im/getgauge/chat?at=5b918a8fac25fd11b5ef2d41)

**Comment by Thunderforge** [comment] 2018-09-07 02:26
In case Gitter ever goes away, here's the error that I get:

```
[11:51:33] :     [Step 3/4] Plugin [Html Report] with pid [2862] did not exit after 4.00 seconds. Forcefully killing it.
[11:51:33] :     [Step 3/4] Specifications:    320 executed    60 passed    260 failed    0 skipped
[11:51:33] :     [Step 3/4] Scenarios:    356 executed    60 passed    296 failed    0 skipped
```

There is no additional log information about why it failed.

Given that this was once fixed, and is now a problem again, then I think a hard 4 second timeout is not the right solution. I know that this is basically the [halting problem](https://en.wikipedia.org/wiki/Halting_problem), but perhaps there is a way that we can more intelligently determine if the HTML Report is hanging.

Can we perhaps change it to check how recent there was activity (perhaps via additional logs at DEBUG level)? Say that every second we check when the last activity was. If the last sign of activity was 4 seconds ago, then kill the process. But if the last sign of activity was less than 4 seconds ago, then wait another second and check again.

Also, I think it would be better to just error hard if we can't create an HTML report instead of creating a partial report that is kind of useless. Would that be a possibility?

**Closed** 2020-07-21 10:55 UTC
Labels: ready for QA
