### ISSUE TITLE
Statistics of passed, failed and skipped do not add up to the total

### ISSUE THREAD

**Issue by sguptatw** [getgauge/html-report#56] opened 2016-04-21 07:03 UTC
### Expected behavior
Statistics of passed, failed and skipped should add up to the total

### Actual behavior
Statistics of passed, failed and skipped do not add up to the total

### Steps to reproduce
1. Create a spec file
```
Specification Heading
=====================

Vowel counts in single word
---------------------------

tags: single word

* something

Vowel counts in single word1
---------------------------

tags: single word

* something1

Vowel counts in multiple word
-----------------------------

This is the second scenario in this specification

Here's a step that takes a table

* somethingelse

```
2. Implement step something and something1 only
```
    @Step("something")
    public void implementation2() {
    }

    @Step("something1")
    public void implementation6() {
        assertEquals(true,false);
    }
```
3. Execute the spec and see the result

[html-report.zip](https://github.com/getgauge/gauge/files/229308/html-report.zip)

### Gauge version
```
Gauge version: 0.4.1.nightly-2016-04-19

Plugins
-------
html-report (2.1.0)
java (0.3.4.nightly-2016-04-19)
```

**Comment by mahendrakariya** [comment] 2016-04-28 09:09
Has been fixed in Gauge core. Please try with Gauge nightly version > 2016-04-28

**Comment by sguptatw** [comment] 2016-05-03 09:12
The console report shows
Specifications:	1 executed	0 passed	1 failed	0 skipped
Scenarios:	2 executed	1 passed	1 failed	1 skipped

However the html report shows 
1 TOTAL SPECS :  1 FAILED   0 PASSED  1 SKIPPED

**Comment by kaustavdm** [comment] 2016-05-18 07:03
Confirmed. Gauge core shows this properly. But html-report messes up the count.

**Comment by sguptatw** [comment] 2016-05-23 07:38
This issue still persists on
```
Gauge version: 0.4.1.nightly-2016-05-18

Plugins
-------
html-report (2.1.1.nightly-2016-05-19)
java (0.4.1.nightly-2016-05-17)
```

**Comment by kaustavdm** [comment] 2016-05-27 09:02
I cannot re-reproduce this any more since the last commit (7fe8edc). So, latest nightly should have this. Requesting QA check.

Here is a test run:

```
$ gauge specs/
[ValidationError] /Users/kaustavd/src/gauge/samples/gauge-sample-java/specs/test1.spec:10: Step implementation not found => 'I am a skipped step'
[ValidationError] /Users/kaustavd/src/gauge/samples/gauge-sample-java/specs/test2.spec:9: Step implementation not found => 'I am a skipped step'
# I am Test2
  ## Test2Scenario1	 ✔

# I am test3
  ## Test3Scenario1	 ✔
  ## Test3Scenario2	 ✔
  ## Test3Scenario3	 ✔

# I am test4
  ## Test4Scenario1	 ✔
  ## Test4Scenario2	 ✔ ✘

        Failed Step: I am a failed step
        Error Message: java.lang.RuntimeException
        Stacktrace:
        StepImplementation.failed(StepImplementation.java:48)
        sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        java.lang.reflect.Method.invoke(Method.java:497)
        com.thoughtworks.gauge.execution.MethodExecutor.execute(MethodExecutor.java:31)
        com.thoughtworks.gauge.execution.StepExecutionStage.executeStepMethod(StepExecutionStage.java:96)
        com.thoughtworks.gauge.execution.StepExecutionStage.executeStep(StepExecutionStage.java:77)
        com.thoughtworks.gauge.execution.StepExecutionStage.execute(StepExecutionStage.java:58)
        com.thoughtworks.gauge.execution.AbstractExecutionStage.executeNext(AbstractExecutionStage.java:24)
        com.thoughtworks.gauge.execution.HookExecutionStage.execute(HookExecutionStage.java:42)
        com.thoughtworks.gauge.execution.ExecutionPipeline.start(ExecutionPipeline.java:31)
        com.thoughtworks.gauge.processor.ExecuteStepProcessor.process(ExecuteStepProcessor.java:34)
        com.thoughtworks.gauge.connection.MessageDispatcher.dispatchMessages(MessageDispatcher.java:72)
        com.thoughtworks.gauge.GaugeRuntime.main(GaugeRuntime.java:37)


  ## Test4Scenario3	 ✔

Sucessfully generated xml-report to => /Users/kaustavd/src/gauge/samples/gauge-sample-java/reports/xml-report
Successfully generated html-report to => /Users/kaustavd/src/gauge/samples/gauge-sample-java/reports/html-report
Specifications:	3 executed	2 passed	1 failed	1 skipped
Scenarios:	7 executed	6 passed	1 failed	2 skipped

Total time taken: 464ms
```

Here is the corresponding html-report:

<img width="952" alt="Gauge html-report screenshot" src="https://cloud.githubusercontent.com/assets/364832/15603242/3b0544c6-2417-11e6-8c54-663543ee27ad.png">

**[Attached html-report](https://github.com/getgauge/html-report/files/286131/html-report.zip)**

**Closed** 2016-05-31 12:18 UTC
Labels: ready for QA, type: bug
