### ISSUE TITLE
All Comments not appearing on the html-report

### ISSUE THREAD

**Issue by sguptatw** [getgauge/html-report#67] opened 2016-05-05 10:57 UTC
### Expected behavior
All the comments provided must be printed on the html-report

### Actual behavior
Any comment starting with a star, though getting treated as comment, is not getting printed in html-report

### Steps to reproduce
1. Create a spec
```
--------
* sfdsf "cd"

kusfdsf sdfsdfsdf
=================
Scenario
--------
* sfdsf "ab"
```
2. Create implementation
```
        [Step("sfdsf <ab>")]
        public void SfdsfSfdwithSfda1(string sdf)
        {
            sdf.Should().NotBe("cd");
        }
```
3. The html-report does not show 
```
-----------
* sfdsf "ab"
```
as comment

### Gauge version
```
Gauge version: 0.4.1.nightly-2016-05-03

Plugins
-------
csharp (0.7.3.nightly-2016-05-03)
html-report (2.1.1.nightly-2016-05-03)
java (0.4.0)
ruby (0.2.0)
xml-report (0.1.2.nightly-2016-05-03)
```

**Comment by apoorvam** [comment] 2016-06-01 06:54
Duplicate of #62 . Closing this for now.

**Closed by apoorvam** 2016-06-01 06:54 UTC
Labels: type: bug
