### ISSUE TITLE
Html report shows the number of spec files that have passed or failed, not the number of scenarios

### ISSUE THREAD

**Issue by FathimaHarris** [getgauge/html-report#92] opened 2016-09-01 08:31 UTC
### Expected behavior

The report could show the number of passed/failed scenarios along with the number of specs that has passed or failed.
### Actual behavior

The report currently shows the number of passed/failed specs
### Gauge version

```
Gauge version: 0.3.0
html-report (2.0.0)
```

**Comment by sguptatw** [comment] 2016-10-13 12:24
Currently in the latest nightly it is showing the number of passed/failed when I click on a given specification. However it is not showing the total count of specs passed or failed.

**Comment by sguptatw** [comment] 2016-10-13 12:32
This is also giving a wrong scenario count in the following case. 
It says 0 failed, 0 passed, 0 skipped.

1. Create a spec
```
Specification Heading
=====================

     |VowelCount|
     |----------|
     |1         |
     |2         |
     |3         |


* Vowels being "aeiou"

Vowel counts in single word
---------------------------

tags: single word

* The word "gauge" has <VowelCount> vowels.

Vowel counts in multiple word
-----------------------------

This is the second scenario in this specification

Here's a step that takes a table

* Almost all words have vowels<VowelCount>

     |Word  |Vowel Count|
     |------|-----------|
     |Gauge |3          |
     |Mingle|2          |
     |Snap  |1          |
     |GoCD  |1          |
     |Rhythm|0          |
```

2. Create a implementation
```
public class StepImplementation {

    private HashSet<Character> vowels;

    @Step({"Vowels in English language are <vowelString>."})
    public void setLanguageVowels(String vowelString) {
        Gauge.writeMessage("here");
        vowels = new HashSet();
        for (char ch : vowelString.toCharArray()) {
            vowels.add(ch);
        }
        Gauge.writeMessage("there");
    }

    @Step("Vowels being <vowelString>")
    public void setLanguageVowels1(String vowelString) {
        vowels = new HashSet();
        for (char ch : vowelString.toCharArray()) {
            vowels.add(ch);
        }
    }

        @Step("The word <word> has <expectedCount> vowels.")
        public void verifyVowelsCountInWord(String word, int expectedCount) {
            int actualCount = countVowels(word);
           // assertEquals(expectedCount, actualCount);
        }

        @Step("Almost all words have vowels<VowelCount> <wordsTable>")
        public void verifyVowelsCountInMultipleWords(int argVowelcount, Table wordsTable) throws Exception {
            if(argVowelcount==3)
                throw new Exception("sdfsdfsdf");
            for (TableRow row : wordsTable.getTableRows()) {
                String word = row.getCell("Word");
                int expectedCount = Integer.parseInt(row.getCell("Vowel Count"));
                int actualCount = countVowels(word);
                assertEquals(expectedCount, actualCount);
            }
        }


    @Step("Almost all words have vowels <wordsTable>")
    public void verifyVowelsCountInMultipleWords(Table wordsTable) {
        for (TableRow row : wordsTable.getTableRows()) {
            String word = row.getCell("Word");
            int expectedCount = Integer.parseInt(row.getCell("Vowel Count"));
            int actualCount = countVowels(word);
            assertEquals(expectedCount, actualCount);
        }
    }

    private int countVowels(String word) {
        int count = 0;
        for (char ch : word.toCharArray()) {
            if (vowels.contains(ch)) {
                count++;
            }
        }
        return count;
    }

    public String getName(ExecutionContext context) {
        String tags = context.getAllTags().toString();
        String scenarioName = context.getCurrentScenario().getName().toString();
        String specName = context.getCurrentSpecification().getName().toString();
        String step = context.getCurrentStep().getText().toString();
        return "spec name \n" + specName + "tags \n" + tags + "scenario \n" + scenarioName + " step \n" + step;
    }
}
```

**Comment by sriv** [comment] 2016-10-17 06:28
@sguptatw:

> However it is not showing the total count of specs passed or failed.

Where do you expect to see the total count and do not see it? I can see the total specs in the report next to the chart. Ref screenshot below:

<img width="1426" alt="screen shot 2016-10-17 at 11 56 04 am" src="https://cloud.githubusercontent.com/assets/389148/19427317/de0ddd9a-9460-11e6-8e6e-0e1bc5355b33.png">

> This is also giving a wrong scenario count in the following case. 
It says 0 failed, 0 passed, 0 skipped.

Again, I see the scenario count matching the execution, ref screenshot above. 

Am I misunderstanding the issue?

**Comment by mahendrakariya** [comment] 2016-11-10 06:30
This is a duplicate of #42 and there has been some discussion on that issue as well. This is note to ensure that #42 has been referred before this issue is closed.

**Comment by nehashri** [comment] 2019-05-16 06:47
The number of scenarios is now shown

**Closed by nehashri** 2019-05-16 06:47 UTC
