### ISSUE TITLE
Green icon for failed test

### ISSUE THREAD

**Issue by sguptatw** [getgauge/html-report#47] opened 2016-04-01 16:52 UTC
With the spec, even though the errors are indicated, the html report has the green icon against the step descriptions
[html-report.zip](https://github.com/getgauge/html-report/files/200002/html-report.zip)

Users should be able to start the game
======================================

User should be able to access the site
--------------------------------------
tags: join

User should be able to join an existing game
--------------------------------------------
tags: search

* Green icon for failed test

**Comment by mahendrakariya** [comment] 2016-04-22 09:49
Duplicate of #52.

**Closed by mahendrakariya** 2016-04-22 09:49 UTC
Labels: bug, duplicate
