### ISSUE TITLE
The Gauge.WriteMessage is not visible in the HTML report

### ISSUE THREAD

**Issue by sguptatw** [getgauge/html-report#148] opened 2017-04-25 05:40 UTC
The Gauge.WriteMessage is not visible in the HTML report

**Steps to replicate**
* Run the specs from the VS IDE
[GaugeProject3.zip](https://github.com/getgauge/html-report/files/953970/GaugeProject3.zip)

The Message is not getting printed in the HTML report.

**Version**
```
Gauge version: 0.8.4.nightly-2017-04-20

Plugins
-------
csharp (0.10.1.nightly-2017-02-17)
html-report (4.0.0.nightly-2017-04-20)
ruby (0.4.0)
xml-report (0.2.0)
```

**Comment by sriv** [comment] 2017-04-26 06:26
`GaugeMessages.WriteMessage` is used in hook, making this issue a duplicate of #111.
Closing.

**Closed by sriv** 2017-04-26 06:26 UTC
Labels: bug, ready
