### ISSUE TITLE
no contents display when open report with chrome on windows

### ISSUE THREAD

**Issue by uzmar** [getgauge/html-report#17] opened 2015-09-07 06:59 UTC
chrome version: 45
env: windows 8.1

<img width="1160" alt="screen shot 2015-09-07 at 12 28 47 pm" src="https://cloud.githubusercontent.com/assets/10433272/9710855/09c3bac6-555c-11e5-993a-d709c70c8740.png">

**Comment by SG57** [comment] 2015-09-11 20:30
This issue only happens when you view reports from the files on your local storage when your URL starts with `file://`.  If you place the reports on a web-server and access them they render as intended.

This only affects chrome and it is classified as a Chrome security feature to prevent malicious pages saved and opened locally from accessing other things on your harddrive.

One solution (which is horrible) is to launch chrome with the following parameter:
```
--allow-file-access-from-files
```

The better, scalable solution would be to catch the exceptions being thrown complaining about origin null and handle the entire web page accordingly (avoid using `replaceState` etc)

**Comment by sriv** [comment] 2015-09-22 06:48
Another user reports this issue. Here is a stacktrace from the browser console:

```
Navigated to file:///C:/foo/reports/html-report/index.html
Error: Failed to execute 'replaceState' on 'History': A history state object with URL 'file:///C:/foo/reports/html-report/index.html#/' cannot be created in a document with origin 'null'.
    at Error (native)
    at se.k.url (file:///C:/foo/reports/html-report/js/angular.min.js:56:127)
    at Vd.a.$get (file:///C:/foo/reports/html-report/js/angular.min.js:107:150)
    at Object.d [as invoke] (file:///C:/foo/reports/html-report/js/angular.min.js:51:488)
    at file:///C:/foo/reports/html-report/js/angular.min.js:53:231
    at c (file:///C:/foo/reports/html-report/js/angular.min.js:51:236)
    at Object.d [as invoke] (file:///C:/foo/reports/html-report/js/angular.min.js:51:453)
    at file:///C:/foo/reports/html-report/js/angular.min.js:53:231
    at c (file:///C:/foo/reports/html-report/js/angular.min.js:51:236)
    at Object.d [as invoke] (file:///C:/foo/reports/html-report/js/angular.min.js:51:453)
 ```

**Comment by Thunderforge** [comment] 2015-09-22 14:59
We've run into this problem too. It did not happen with the previous version of the HTML-report plugin. We can see everything fine on Firefox.

**Comment by mahendrakariya** [comment] 2015-10-03 06:11
Reports are getting rendered perfectly fine if they are accessed from some http server. But if accessed using `file:\\\` in the url, it is throwing error.


**Workaround (using http server):**
  1. Install node http-server by running `npm install -g http-server`
  2. Navigate to the reports directory where `index.html` file is present and run the command `http-server`.
  3. Open http://localhost:8080 (or the port at which the server is running) in Chrome.

**Comment by mahendrakariya** [comment] 2015-10-03 06:41
@SG57 Gauge uses angularjs to generate the html reports. `replaceState` is used within angular. So there's no way for us to avoid it. 

Moreover, this issue is not just with angularjs apps, but also with other frameworks like jqmobile, as reported on [chrome bug tracker](https://code.google.com/p/chromium/issues/detail?id=528681#c12). So we'd prefer to wait for the fix or some workaround from the chrome team.

**Comment by Thunderforge** [comment] 2015-10-03 11:16
How is it that older versions of Gauge and the HTML report plugin render correctly on Chrome if this is an issue in Chrome itself? We can see it find in the latest version of Chrome if it is generated by Gauge 0.17 and the previous version of HTML report. But we cannot se it if it is generated by the latest version. Because the version of Chrome has not changed, this sounds like an error on the Gauge side.

**Comment by mahendrakariya** [comment] 2015-10-03 11:52
@Thunderforge I understand your point. To get to the root of the issue, could you please let us know what version of Google Chrome you are currently using?

Let me also add some details about how Gauge reports are generated. 

Gauge core simply dumps the results in json format. The html-report plugin (which is an AngularJS app), then consumes this json and renders the page on the browser. 

Since we can see the reports perfectly fine on other browsers, there shouldn't be any issue in the JSON which is being generated by Gauge core. The [latest version](https://github.com/getgauge/html-report/releases) of html-report plugin is 1.0.4, and it was released on June 18. We haven't released any new version of the html-report plugin after that.

As you said, it was working earlier. It has stopped working only recently. And the only thing that has changed in past few weeks is that Google has released [Chrome version 45](http://googlechromereleases.blogspot.in/2015/09/stable-channel-update.html), on Sept 1. Moreover this [bug](https://code.google.com/p/chromium/issues/detail?id=528681) is only on Chrome 45 as per chrome bug tracker. 

So, could you please confirm your Chrome version? If you are facing this issue on an older version of Chrome, then it's very likely that there might be something wrong on our side.

**Comment by Thunderforge** [comment] 2015-10-05 15:04
I double-checked my machine and am using Chrome version 45 and html-report 1.0.4. If I view reports generated by Gauge 0.1.7, I can view reports in Chrome. If I view reports generated by 0.1.8, I cannot. I've even had the reports loaded in tabs right next to each other in Chrome. I know you said that it's unlikely that there is an issue with the JSON being generated by the Gauge core, but that is what I see on my machine.

**Comment by mahendrakariya** [comment] 2015-10-05 15:10
@Thunderforge Thanks for this info. We will take a look.

**Comment by mahendrakariya** [comment] 2015-10-09 08:17
@Thunderforge we generated reports using Gauge 0.1.7 on multiple Windows machines (both Windows 7 and Windows 8). We weren't able to open any of the reports on Chrome 45.

**Comment by Thunderforge** [comment] 2015-10-09 15:19
We investigated further and found that the issue was not the version of Gauge installed, but the URL. If it ends with `html-report/index.html`, then the page does not appear properly in Chome. But if you end the URL in `html-report/index.html#/` (requires a page refresh if you append it to a URL without it), it appears properly. This happens in both Gauge 0.1.7 and 0.1.8.

It seems that on our machines running 0.1.7, we had the version ending with `#/` bookmarked. Our 0.1.8 machines did not. I'm not sure how we originally came to that ending.

So it appears that with the latest HTML report plugin, latest Chrome version, Windows 7 (and newer?), and either Gauge 0.1.7 or Gauge 0.1.8, the report will only appear properly if you add `#/` to the end of the URL. It works either way in Firefox and other browsers.

**Comment by mahendrakariya** [comment] 2015-10-10 07:33
This is interesting. Thanks for the analysis!

We have also updated the [issue on chrome bug tracker](https://code.google.com/p/chromium/issues/detail?id=528681#c18) with these details so that the chrome team can take a look at it.

**Comment by MattFenner** [comment] 2015-11-17 07:09
i am getting this too with chrome version 46

**Comment by mahendrakariya** [comment] 2015-11-17 08:50
@MattFenner We just checked. This bug which was introduced in Chrome v45 is not yet fixed. Until Google releases a fix for this bug, we would recommend using either [HTTP server](https://github.com/getgauge/html-report/issues/17#issuecomment-145209277) or [add `#/` to the path](https://github.com/getgauge/html-report/issues/17#issuecomment-146901279) as suggested by @Thunderforge.

**Comment by kaustavdm** [comment] 2015-12-17 11:16
This should be fixed now. Please confirm if this works for you.

**Comment by kaustavdm** [comment] 2015-12-18 11:04
Tested. Works for me. Closing this unless someone can reproduce this bug.

**Comment by mahendrakariya** [comment] 2015-12-30 08:45
This bug is not yet fixed. Tried on Chrome 47 / Windows 8. Was able to reproduce it.

**Comment by kaustavdm** [comment] 2015-12-30 11:12
@mahendrakariya Do you see any JS errors in the browser console?

**Closed** 2015-12-31 06:00 UTC
Labels: bug
