### ISSUE TITLE
Data driven spec reports show all rows for the spec, not just the rows its executed for

### ISSUE THREAD

**Issue by bharat2014** [getgauge/html-report#49] opened 2016-04-06 20:09 UTC
Executing a spec for a specific row of the data table creates a report with all the rows from the data table with incorrect marking of failed row. If the spec is executed for n-th row and it fails, in the report all the rows are displayed and failure is marked on the first row of the data table.

**Comment by sguptatw** [comment] 2016-04-07 08:50
@bharat2014 : Please mention the gauge and gauge-html version you are currently using. It will aslo be helpful if you can give us more details of the spec. As we are not able to replicate it on the latest.

**Comment by mahendrakariya** [comment] 2016-04-28 09:55
This issue is a duplicate of #50. We will be tracking it there.

**Closed by mahendrakariya** 2016-04-28 09:55 UTC
Labels: duplicate
