### ISSUE TITLE
All the failed tests are reported in a successful state in the HTML report with Appium

### ISSUE THREAD

**Issue by zbrea** [getgauge/html-report#277] opened 2021-07-12 16:50 UTC
### Expected behavior
In the tests which cannot find elements (id) on the screen of the app, must have passed in error in the logs and in the html reporting.

### Actual behavior
all tests are successfully passed., even if they cannot find elements (id) on the screen of the app, since I started using gauge-java, for Appium for a native application.

### Steps to reproduce
When I run my tests which must fail, I have the impression that the html-report extension does not manage the drivers on Appium.
You will find the details of the logs here. I deleted the personal info in the logs)

### Gauge version
❯ gauge -v
Gauge version: 1.3.2
Commit Hash: 063444f

Plugins
-------
flash (0.0.2)
html-report (4.1.0)
java (0.7.15)
json-report (0.3.6)
screenshot (0.1.0)
spectacle (0.1.4)
xml-report (0.2.3)

Log : (I submitted a short log to facilitate readability)
---------------------------------------------
![Log](https://user-images.githubusercontent.com/59898499/125471957-d25b4fb6-8162-42b3-99e1-01dd25e50fa1.JPG)

**Comment by sriv** [comment] 2021-07-13 03:37
This is not a problem with html-report. Rather it seems that your tests are not getting marked as `failed` when the exceptions occur.

if you notice your console log, you'll see gauge sees all scenarios as passed.

Can you share what a sample project? or at least what is the implementation of the step where the error occurs?

**Comment by zbrea** [comment] 2021-07-13 15:10
Thank you for your quick response !
I put the same code in a new project created via gauge init, and suddenly the code works fine, it shows the error in the reporting.

It is casement the same code, I do not understand the problem.
I am analyzing my old project file set to find out where the problem is.
Log in the new project :
-----------------------
![Log2](https://user-images.githubusercontent.com/59898499/125476997-59be79d6-67de-4170-a267-c30c70cc95bd.JPG)

**Comment by sriv** [comment] 2021-07-13 16:22
I suspect that the error in your project is getting handled somewhere and thus the project is not propogating an exception to gauge (which is something gauge needs to identify a failure, ex. assert will throw an exception on failure which gauge will analyse and report_

**Comment by zbrea** [comment] 2021-07-13 20:20
Thank you very much for your tip, you are the best.
It's been over a week since I have been on this problem, I never thought that if I handle the error by myself, it will be ignored by gauge.
I think you have to remember to take into account the errors handled by try/catch or throw.
The first thing a developer will think about is to handle errors with try / catch.
  
I just deleted the try / catch, suddenly it works fine with a nice screenshot from my smartphone app.

Here is an example of a method handled by a try catch:

   @Step("sendKey <id> with <text>")
    public void sendKey(String id, String text) {
        try {
            driver.findElement(By.id(id)).sendKeys(text);
        } catch (Exception ex) {
            System.out.println("This element '" + id + "' is not found  : " + ex);
        }
    }

**Comment by sriv** [comment] 2021-07-14 01:58
Hi, some notes below:

> The first thing a developer will think about is to handle errors with try / catch. You think that it is possible of an evolution to manage it differently ?

The norm AFAIK is that if you want the error to propagate, then you rethrow the exception in the `catch` block. Most testing libraries rely on exceptions to ascertain failure conditions. Take for example the junit assert. If you were to wrap `assert` in a try/catch, you'd notice that the tests are reported as passed even when the assert fails.

> Even when I use the Custom messages in reports, it displays the error message in a step that is green (color) successful, which is paradoxical...

`Gauge.writeMessage` is a function that takes a string and puts it into the report. It has no sematic knowledge of what the string represents. The green colour is indicative of the fact that the scenario passed (i.e. no exceptions were passed on).

Gauge, by design, is framework agnostic and it relies on users to feed it the right inputs. I can understand this being a learning curve, but unless we tune Gauge to certain use cases, it will be tough to get this intelligence IMO. If you have ideas, please raise issues! It will be most interesting and helpful.

> The reporting must be understandable by a non-technical person 

I agree with this principle, but it is upto the individual writing the tests to bubble up the right contextual, domain specific message to the report.

**Closed** 2021-07-14 16:40 UTC
